---
language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
script: bundle exec rake spec SPEC_OPTS='--format documentation'
env:
  matrix:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0"
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
