name          'puppet-couchpotato'
version       '0.0.1'
source        'https://github.com/DexterTheDragon/puppet-couchpotato'
author        'DexterTheDragon'
license       'Apache License, Version 2.0'
summary       'Module to install couchpotato'
description   'Installs and configures couchpotato'
project_page  'https://github.com/DexterTheDragon/puppet-couchpotato'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/vcsrepo'
